### ISSUE TITLE
it is not working for the new race line

### ISSUE THREAD

**Issue by riverlthe** [lulu2002/DeepRacerAnalytics#59]
polyfills.904996afc50e72d7221a.js:1          GET https://lulu2002.github.io/DeepRacerAnalytics/assets/tracks/2022_june_pro.npy 404
(anonymous) @ polyfills.904996afc50e72d7221a.js:1
I.s.<computed> @ polyfills.904996afc50e72d7221a.js:1
load @ main.24c176bbbe2b371c8b74.js:1
loadTrackByName @ main.24c176bbbe2b371c8b74.js:1
(anonymous) @ main.24c176bbbe2b371c8b74.js:1
invoke @ polyfills.904996afc50e72d7221a.js:1
onInvoke @ main.24c176bbbe2b371c8b74.js:1
invoke @ polyfills.904996afc50e72d7221a.js:1
run @ polyfills.904996afc50e72d7221a.js:1
(anonymous) @ polyfills.904996afc50e72d7221a.js:1
invokeTask @ polyfills.904996afc50e72d7221a.js:1
onInvokeTask @ main.24c176bbbe2b371c8b74.js:1
invokeTask @ polyfills.904996afc50e72d7221a.js:1
runTask @ polyfills.904996afc50e72d7221a.js:1
m @ polyfills.904996afc50e72d7221a.js:1
invokeTask @ polyfills.904996afc50e72d7221a.js:1
g @ polyfills.904996afc50e72d7221a.js:1
k @ polyfills.904996afc50e72d7221a.js:1
main.24c176bbbe2b371c8b74.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'data')
TypeError: Cannot read properties of undefined (reading 'data')
    at main.24c176bbbe2b371c8b74.js:1:757288
    at l.invoke (polyfills.904996afc50e72d7221a.js:1:7234)
    at Object.onInvoke (main.24c176bbbe2b371c8b74.js:1:717163)
    at l.invoke (polyfills.904996afc50e72d7221a.js:1:7174)
    at i.run (polyfills.904996afc50e72d7221a.js:1:2646)
    at polyfills.904996afc50e72d7221a.js:1:17418
    at l.invokeTask (polyfills.904996afc50e72d7221a.js:1:7852)
    at Object.onInvokeTask (main.24c176bbbe2b371c8b74.js:1:716979)
    at l.invokeTask (polyfills.904996afc50e72d7221a.js:1:7773)
    at i.runTask (polyfills.904996afc50e72d7221a.js:1:3261)
    at Z (polyfills.904996afc50e72d7221a.js:1:16623)
    at Z (polyfills.904996afc50e72d7221a.js:1:16160)
    at polyfills.904996afc50e72d7221a.js:1:17455
    at l.invokeTask (polyfills.904996afc50e72d7221a.js:1:7852)
    at Object.onInvokeTask (main.24c176bbbe2b371c8b74.js:1:716979)
    at l.invokeTask (polyfills.904996afc50e72d7221a.js:1:7773)
    at i.runTask (polyfills.904996afc50e72d7221a.js:1:3261)
    at m (polyfills.904996afc50e72d7221a.js:1:9846)

**Comment by lulu2002** [comment]
Thanks for reporting this, gonna add new tracks asap.

**Comment by lulu2002** [comment]
Is it supported now?
